import { chromium, webkit } from 'playwright';
import { createApp } from '../server.js';
import { mkdtemp, mkdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const dataDir=await mkdtemp(path.join(tmpdir(),'slidelink-browser-'));
const app=await createApp({dataDir,uploadKey:''});
await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${app.server.address().port}`;
const browser=await (process.env.TEST_WEBKIT?webkit:chromium).launch(process.env.TEST_CHROME?{channel:'chrome',headless:true}:{headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(base);
 assert.equal(await page.locator('html').getAttribute('lang'),'en');
 await page.locator('[data-language]').selectOption('zh');
 assert.equal(await page.locator('#new-project').textContent(),'新建项目');
 await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'zh-CN');
 await page.locator('[data-language]').selectOption('en');await page.getByRole('button',{name:'New folder',exact:true}).click();await page.getByRole('textbox',{name:'Name',exact:true}).fill('学术汇报');await page.locator('#name-form').getByRole('button',{name:'Save',exact:true}).click();await page.locator('#name-dialog').waitFor({state:'hidden'});
 await page.locator('#folders button').click();await page.locator('#demo').click();await page.locator('#save-button:not([disabled])').waitFor();
 await page.locator('#preview-notes').fill('上传时编辑的私人讲稿。');
 await page.locator('#preview-next').click();await page.locator('#preview-notes').fill('Remember the pronunciation of this word.\n\n'+Array.from({length:18},(_,i)=>`Reading paragraph ${i+1}: notes and annotations remain private.`).join('\n\n'));
 await page.locator('#save-button').click();await page.locator('#project-view:not([hidden])').waitFor();
 let rows=page.locator('.version-card');assert.equal(await rows.count(),1);
 const screenLink=await rows.first().getByRole('link',{name:'Open screen',exact:true}).getAttribute('href');const presenterLink=await rows.first().getByRole('link',{name:'Open presenter',exact:true}).getAttribute('href');
 await page.locator('#new-version').click();await page.locator('#html-file').setInputFiles({name:'revision.html',mimeType:'text/html',buffer:Buffer.from((await readFile('public/examples/demo.html','utf8')).replace('<h1>Sample presentation</h1>','<h1>Revised sample cover</h1>'))});await page.locator('#notes-file').setInputFiles('public/examples/notes.txt');await page.locator('#version-label').fill('修改稿');await page.locator('#preview-button').click();await page.locator('#save-button:not([disabled])').waitFor();await page.locator('#save-button').click();await page.waitForFunction(()=>document.querySelectorAll('.version-card').length===2);
 await page.locator('#back').click();await page.locator('.project-cover[data-loaded=true]').waitFor();
 assert.equal(await page.frameLocator('.project-cover iframe').locator('h1').textContent(),'Revised sample cover');
 await page.locator('.project-card').click();
 const screenContext=await browser.newContext({viewport:{width:1440,height:900}}), presenterContext=await browser.newContext({viewport:{width:1194,height:834},hasTouch:true});
 const screen=await screenContext.newPage(),presenter=await presenterContext.newPage();
 for(const p of [screen,presenter])p.on('pageerror',e=>errors.push(e.message));
 presenter.on('dialog',d=>d.accept());
 await screen.goto(base+screenLink);await presenter.goto(base+presenterLink);
 await presenter.locator('#fatal').waitFor({state:'hidden'});await screen.locator('#fatal').waitFor({state:'hidden'});
 await presenter.waitForFunction(()=>window.SlideLink?.link?.status().startsWith('Screen linked'));
 assert.equal(await presenter.locator('#notes-text').textContent(),'上传时编辑的私人讲稿。');
 assert.equal(await screen.locator('#notes-pane').count(),0);
 await presenter.locator('#next').click();await screen.waitForFunction(()=>window.SlideLink.link.state().slide===1);
 const box=await presenter.locator('.ink-page:not([hidden])').boundingBox();
 async function pen(p,target,points){await p.locator(target).dispatchEvent('pointerdown',{pointerId:21,pointerType:'pen',isPrimary:true,pressure:.6,clientX:points[0][0],clientY:points[0][1],buttons:1});for(const [x,y]of points.slice(1))await p.locator(target).dispatchEvent('pointermove',{pointerId:21,pointerType:'pen',isPrimary:true,pressure:.6,clientX:x,clientY:y,buttons:1});await p.locator(target).dispatchEvent('pointerup',{pointerId:21,pointerType:'pen',isPrimary:true,clientX:points.at(-1)[0],clientY:points.at(-1)[1]});}
 await pen(presenter,'.ink-page:not([hidden])',[[box.x+100,box.y+100],[box.x+180,box.y+140],[box.x+240,box.y+100]]);
 await screen.waitForFunction(()=>document.querySelector('.ink-page:not([hidden]) .sl-ink path')?.getAttribute('d')?.length>10);
 const firstPath=await screen.locator('.ink-page:not([hidden]) .sl-ink path').getAttribute('d');
 // The same selected tool works on notes directly, without a private-pen mode.
 await presenter.locator('.sl-bar [data-t="b"]').click();
 const nb=await presenter.locator('#notes-content').boundingBox();
 await pen(presenter,'#notes-content',[[nb.x+34,nb.y+54],[nb.x+80,nb.y+54],[nb.x+125,nb.y+54]]);
 await presenter.locator('#notes-ink path').waitFor();
 assert.equal(await presenter.locator('#notes-ink path').getAttribute('fill'),'#1d5fd1');
 const noteBefore=await presenter.locator('#notes-ink path').getAttribute('d');
 await presenter.locator('#font-plus').click();
 await presenter.waitForFunction(d=>document.querySelector('#notes-ink path').getAttribute('d')!==d,noteBefore);
 await presenter.locator('#font-minus').click();
 await presenter.locator('.sl-bar [data-t="h"]').click();
 await pen(presenter,'#notes-content',[[nb.x+36,nb.y+105],[nb.x+130,nb.y+105],[nb.x+210,nb.y+105]]);
 assert.equal(await presenter.locator('#notes-ink .note-highlighter').count(),1);
 assert.equal(await screen.locator('.ink-page:not([hidden]) .sl-ink path').count(),1);
 await presenter.locator('#private-undo').click();assert.equal(await presenter.locator('#notes-ink path').count(),1);
 await presenter.locator('#private-redo').click();assert.equal(await presenter.locator('#notes-ink path').count(),2);
 await presenter.locator('#private-clear').click();assert.equal(await presenter.locator('#notes-ink path').count(),0);
 await presenter.locator('#private-undo').click();assert.equal(await presenter.locator('#notes-ink path').count(),2);
 await presenter.locator('.sl-bar [data-t="x"]').click();
 await pen(presenter,'#notes-content',[[nb.x+60,nb.y+54],[nb.x+120,nb.y+54]]);
 assert.equal(await presenter.locator('#notes-ink path').count(),1);
 await presenter.locator('#private-undo').click();
 await presenter.locator('.sl-bar [data-t="b"]').click();
 // Scroll positions are remembered independently for each page.
 await presenter.locator('#notes-scroll').evaluate(el=>{el.scrollTop=300;});
 await presenter.waitForFunction(()=>document.querySelector('#notes-scroll').scrollTop===300);
 await presenter.locator('#next').click();await presenter.locator('#previous').click();
 assert.equal(await presenter.locator('#notes-scroll').evaluate(el=>el.scrollTop),300);
 await presenter.locator('#notes-scroll').evaluate(el=>{el.scrollTop=0;});
 // Force a genuine network interruption: separate browser contexts cannot use BroadcastChannel.
 await presenterContext.setOffline(true);await presenter.waitForFunction(()=>!window.SlideLink.link.state().relays[0].up);await presenter.locator('#next').click();await presenterContext.setOffline(false);await screen.waitForFunction(()=>window.SlideLink.link.state().slide===2);
 await presenter.locator('#previous').click();await screen.waitForFunction(()=>window.SlideLink.link.state().slide===1);
 await screen.reload();await screen.waitForFunction(()=>document.querySelector('.ink-page:not([hidden]) .sl-ink path')?.getAttribute('d')?.length>10);assert.equal(await screen.locator('.ink-page:not([hidden]) .sl-ink path').getAttribute('d'),firstPath);
 await presenter.reload();await presenter.locator('#fatal').waitFor({state:'hidden'});assert.equal(await presenter.locator('#notes-ink path').count(),2);
 await presenter.locator('#edit-notes').click();await presenter.locator('#notes-editor').fill('演讲中修改的讲稿，不应发给观众。');
 await presenter.locator('[data-language]').selectOption('zh');
 assert.equal(await presenter.locator('#edit-notes').textContent(),'完成编辑');
 assert.equal(await presenter.locator('#notes-editor').inputValue(),'演讲中修改的讲稿，不应发给观众。');
 assert.equal(await presenter.locator('#note-page').textContent(),'第 2 页');
 await presenter.locator('[data-language]').selectOption('en');
 assert.equal(await presenter.locator('#edit-notes').textContent(),'Done editing');
 await presenter.locator('#edit-notes').click();
 const editedBox=await presenter.locator('#notes-content').boundingBox();
 await presenter.locator('.sl-bar [data-t="h"]').click();
 await pen(presenter,'#notes-content',[[editedBox.x+34,editedBox.y+52],[editedBox.x+100,editedBox.y+52],[editedBox.x+190,editedBox.y+52]]);
 await presenter.locator('#save-notes').click();await presenter.locator('#saved-links:not([hidden])').waitFor();
 const revisedLink=await presenter.locator('#saved-links a').first().getAttribute('href');
 const revisedRoom=new URL(base+revisedLink).searchParams.get('room');assert.notEqual(revisedRoom,new URL(base+presenterLink).searchParams.get('room'));
 const saved=await context.request.get(`${base}/api/decks/${revisedRoom}`,{headers:{Authorization:`Bearer ${revisedLink.split('#')[1]}`}});const savedDeck=await saved.json();assert.equal(savedDeck.notes[1],'演讲中修改的讲稿，不应发给观众。');assert(savedDeck.notesInk.pages[1].strokes.length>0);
 assert.equal(await screen.locator('body').textContent().then(s=>s.includes('演讲中修改')),false);
 // A new browser tab restores annotations from the saved version, not session storage.
 const reopened=await presenterContext.newPage();reopened.on('pageerror',e=>errors.push(e.message));
 await reopened.goto(base+revisedLink);await reopened.locator('#fatal').waitFor({state:'hidden'});await reopened.locator('#next').click();
 await reopened.locator('#notes-ink .note-highlighter').waitFor();
 assert.equal(await reopened.locator('#save-notes').isEnabled(),false);
 await reopened.close();
 await mkdir('test-results',{recursive:true});await presenter.screenshot({path:'test-results/presenter.png'});
 await page.bringToFront();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
 await page.waitForFunction(()=>document.querySelectorAll('.version-card').length===3);
 await page.locator('#back').click();
 await page.locator('.project-cover[data-loaded=true]').waitFor();
 await page.frameLocator('.project-cover iframe').locator('h1').waitFor();
 assert.equal(await page.frameLocator('.project-cover iframe').locator('h1').textContent(),'Sample presentation');
 assert.equal(await page.locator('.project-cover iframe').getAttribute('sandbox'),'');
 await page.locator('[data-language]').selectOption('zh');
 assert.equal(await page.locator('.project-name').textContent(),'Sample presentation');
 assert.equal(await page.locator('.project-pages').textContent(),'3 页');
 await page.locator('[data-language]').selectOption('en');
 await page.locator('.project-cover[data-loaded=true]').waitFor();
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:'test-results/library.png',fullPage:true});
 if(process.env.ORIGINAL_HTML){await page.locator('#new-project').click();await page.locator('#title').fill('Super Learning · compatibility test');await page.locator('#html-file').setInputFiles(process.env.ORIGINAL_HTML);await page.locator('#preview-button').click();await page.locator('#save-button:not([disabled])').waitFor();assert((await page.locator('#preview-count').textContent()).includes('43'));await page.frameLocator('#preview-frame').locator('.slidelink-page h1').waitFor({state:'visible'});await page.screenshot({path:'test-results/original-preview.png'});}
 assert.deepEqual(errors,[]);
 console.log('PASS: shared note tools, anchored ink, undo/redo, private version persistence, scroll restoration, refreshed history, bilingual UI, covers, mobile layout, isolated sync, reconnect, and reload.');
} finally {await browser.close();await app.close();}
